"""Regenerate README.md's "Glossary" section from `glossary.py`.

The exact counterpart of `render_stage_docs.py`, for `ROADMAP.md` sec 21 J3's
term list rather than sec 21 J2's per-stage docs, and for the same reason:
the report renders `tsfm_lens.glossary.GLOSSARY` live on every run while the
README is static text, so this script is the only mechanism that keeps the
two in sync. Run it after editing `tsfm_lens/glossary.py`, or with `--check`
in CI to fail on a README that has gone stale.

Usage:
    python render_glossary.py            # rewrite README.md in place
    python render_glossary.py --check    # exit 1 if README.md is stale
    python render_glossary.py --print    # print the generated block only
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tsfm_lens import glossary

_BEGIN = "<!-- BEGIN GLOSSARY (generated by render_glossary.py from tsfm_lens/glossary.py -- edit that file and re-run the script, do not hand-edit this block) -->"
_END = "<!-- END GLOSSARY -->"


def generated_block() -> str:
    return _BEGIN + "\n" + glossary.render_markdown() + _END


def _splice(readme_text: str, block: str) -> str:
    start = readme_text.index(_BEGIN)
    end = readme_text.index(_END) + len(_END)
    return readme_text[:start] + block + readme_text[end:]


def main() -> int:
    args = sys.argv[1:]
    readme_path = Path(__file__).resolve().parent / "README.md"
    block = generated_block()

    if "--print" in args:
        print(block)
        return 0

    current = readme_path.read_text(encoding="utf-8")
    updated = _splice(current, block)

    if "--check" in args:
        if updated != current:
            print(f"README.md's glossary section is stale relative to "
                  f"glossary.py -- run `python {Path(__file__).name}` to regenerate it.",
                  file=sys.stderr)
            return 1
        print("README.md's glossary section matches glossary.py.")
        return 0

    if updated != current:
        readme_path.write_text(updated, encoding="utf-8")
        print(f"README.md regenerated ({readme_path}).")
    else:
        print("README.md already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
