"""CLI for the Chronos-T5 scaling ladder (ROADMAP.md sec 20 H1).

Two modes, because a ladder is two jobs with a long gap between them:

  --emit-configs DIR   expand `configs/scaling_ladder_chronos.yaml`'s `ladder:`
                       block into one ordinary run.py config per rung, and
                       print the commands in cheapest-first order. This is the
                       only place the five configs are written, so a change to
                       the shared body cannot drift between rungs.

  --runs A,B,C ...     reduce the finished run directories into one
                       metric-vs-size table. Loads no model and re-runs
                       nothing; see analysis/scaling_ladder.py for why the
                       significance test is an exact permutation rather than a
                       bootstrap, and why "flat" is sometimes withheld.

Usage:
    python run_scaling_ladder.py --config configs/scaling_ladder_chronos.yaml \
        --emit-configs configs/_ladder
    python run_scaling_ladder.py --runs runs/ladder_tiny,runs/ladder_base \
        --model Chronos --out runs/ladder/scaling_ladder.json
"""

from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tsfm_lens.analysis.scaling_ladder import run_scaling_ladder  # noqa: E402
from tsfm_lens.utils import log  # noqa: E402


def emit_configs(config_path: Path, out_dir: Path) -> list[dict]:
    raw = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    ladder = raw.pop("ladder", None)
    if not ladder:
        raise SystemExit(f"{config_path} has no `ladder:` block -- nothing to expand")
    model_name = ladder["model"]
    names = [m.get("name") for m in raw.get("models", [])]
    if model_name not in names:
        raise SystemExit(f"ladder.model={model_name!r} is not one of the config's "
                         f"models {names} -- refusing to guess which block to vary")

    out_dir.mkdir(parents=True, exist_ok=True)
    base_name = (raw.get("run") or {}).get("name", "ladder")
    written = []
    for rung in ladder["rungs"]:
        cfg = copy.deepcopy(raw)
        cfg["run"]["name"] = f"{base_name}_{rung['label']}"
        for block in cfg["models"]:
            if block.get("name") == model_name:
                block["checkpoint"] = rung["checkpoint"]
                if rung.get("batch_size") is not None:
                    block["batch_size"] = rung["batch_size"]
        title = (cfg.get("report") or {}).get("title", "")
        cfg.setdefault("report", {})["title"] = f"{title} -- {rung['label']} ({rung['checkpoint']})"
        path = out_dir / f"{base_name}_{rung['label']}.yaml"
        path.write_text(
            "# GENERATED by run_scaling_ladder.py --emit-configs. Do not edit by hand:\n"
            "# edit configs/scaling_ladder_chronos.yaml and re-emit, so every rung\n"
            "# keeps a byte-identical shared body (CLAUDE.md sec 11.24).\n"
            + yaml.safe_dump(cfg, sort_keys=False),
            encoding="utf-8")
        written.append({"label": rung["label"], "config": str(path),
                        "run_dir": f"{(cfg.get('run') or {}).get('out_dir', 'runs')}/"
                                   f"{cfg['run']['name']}"})
    return written


def _fmt(v, nd=4):
    return "n/a" if v is None else (f"{v:.{nd}f}" if isinstance(v, float) else str(v))


def print_table(result: dict) -> None:
    rungs = result["rungs"]
    print(f"\nLadder model: {result['ladder_model']}   rungs: {len(rungs)}")
    for r in rungs:
        print(f"  {r['label']:<24} {r['n_params']/1e6:>8.1f}M  {r['checkpoint']}")
    for ex in result["excluded"]:
        print(f"  EXCLUDED {ex['run_dir']}: {ex['reason']}")
    if not result["coverage_is_constant"]:
        print("  ! captured-FLOP fraction is NOT constant across rungs "
              "-- depth-located columns are not strictly comparable "
              f"({result['capture_coverage']})")

    print(f"\n{'metric':<26} {'rho':>7} {'p':>8} {'shape':<20} {'flat':<6} {'range':>9}  values")
    for key, m in result["metrics"].items():
        flat = "?" if m.get("flat") is None else ("yes" if m["flat"] else "no")
        vals = " ".join(f"{v:.3f}" for v in m["values"])
        print(f"{key:<26} {_fmt(m.get('rho'), 3):>7} {_fmt(m.get('p'), 4):>8} "
              f"{m['shape']:<20} {flat:<6} {m['range']:>9.4f}  {vals}")
        if m.get("missing_rungs"):
            print(f"{'':<26} (missing at: {', '.join(m['missing_rungs'])})")
    floors = {m.get("p_floor") for m in result["metrics"].values() if m.get("p_floor")}
    if floors:
        print(f"\np floor for this ladder length: {min(floors):.4f} -- no metric can score "
              f"below it, however strong. Read a p at the floor as 'as extreme as "
              f"{len(rungs)} rungs permit', not as a strong result.")
    unbacked = [k for k, m in result["metrics"].items() if m.get("flat") is None]
    if unbacked:
        print(f"flatness withheld (no within-run CI): {', '.join(unbacked)}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Chronos-T5 scaling ladder (ROADMAP.md sec 20 H1)")
    ap.add_argument("--config", default="", help="ladder config to expand with --emit-configs")
    ap.add_argument("--emit-configs", default="", help="directory to write per-rung configs into")
    ap.add_argument("--runs", default="", help="comma-separated finished run directories")
    ap.add_argument("--model", default="", help="name of the model whose size varies")
    ap.add_argument("--out", default="", help="path to write the ladder JSON to")
    args = ap.parse_args()

    if args.emit_configs:
        if not args.config:
            raise SystemExit("--emit-configs needs --config")
        written = emit_configs(Path(args.config), Path(args.emit_configs))
        print("Wrote per-rung configs (run in this order -- cheapest first):\n")
        for w in written:
            print(f"  python run.py --config {w['config']}")
        print("\nThen reduce them:\n")
        print("  python run_scaling_ladder.py --runs "
              + ",".join(w["run_dir"] for w in written)
              + " --model <ladder model> --out runs/scaling_ladder.json")
        return

    if not args.runs:
        raise SystemExit("give either --emit-configs or --runs")
    if not args.model:
        raise SystemExit("--runs needs --model (the model whose size varies across the ladder)")
    run_dirs = [r.strip() for r in args.runs.split(",") if r.strip()]
    result = run_scaling_ladder(run_dirs, args.model)
    print_table(result)
    if args.out:
        out = Path(args.out)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(result, indent=2, default=float), encoding="utf-8")
        log.info(f"scaling ladder written to {out}")


if __name__ == "__main__":
    main()
