"""Regenerate README.md's "What each stage tells you" section from `stage_docs.py`.

`ROADMAP.md` sec 21 J2's whole point is that the report and the docs cannot
drift apart, because both render the same `tsfm_lens.stage_docs.STAGE_DOCS`
dict. The report renders it live, every run; the README is static text, so
this script is the mechanism that keeps it in sync -- run it after editing
`tsfm_lens/stage_docs.py`, or run it with `--check` in CI/a pre-commit hook
to catch a README that's gone stale.

Usage:
    python render_stage_docs.py            # rewrite README.md in place
    python render_stage_docs.py --check    # exit 1 if README.md is stale
    python render_stage_docs.py --print    # print the generated block only
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from tsfm_lens import stage_docs
from tsfm_lens.pipeline import stage_names

_BEGIN = "<!-- BEGIN STAGE_DOCS (generated by render_stage_docs.py from tsfm_lens/stage_docs.py -- edit that file and re-run the script, do not hand-edit this block) -->"
_END = "<!-- END STAGE_DOCS -->"


def generated_block() -> str:
    return _BEGIN + "\n" + stage_docs.render_markdown(stage_names()) + _END


def _splice(readme_text: str, block: str) -> str:
    start = readme_text.index(_BEGIN)
    end = readme_text.index(_END) + len(_END)
    return readme_text[:start] + block + readme_text[end:]


def main() -> int:
    args = sys.argv[1:]
    readme_path = Path(__file__).resolve().parent / "README.md"
    block = generated_block()

    if "--print" in args:
        print(block)
        return 0

    current = readme_path.read_text(encoding="utf-8")
    updated = _splice(current, block)

    if "--check" in args:
        if updated != current:
            print(f"README.md's stage-docs section is stale relative to "
                  f"stage_docs.py -- run `python {Path(__file__).name}` to regenerate it.",
                  file=sys.stderr)
            return 1
        print("README.md's stage-docs section matches stage_docs.py.")
        return 0

    if updated != current:
        readme_path.write_text(updated, encoding="utf-8")
        print(f"README.md regenerated ({readme_path}).")
    else:
        print("README.md already up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
